export const ASSET_IMPORT_SCHEMA_V1 = Object.freeze({
  id: 'alcoeste.asset-import',
  version: '1.0.0',
  source: {
    primarySheet: 'Base Montagem',
    locationSheet: 'TAG Localização',
    headerRow: 1,
    primaryRequiredHeaders: ['TAG', 'Descrição do MIS', 'Código', 'Status', 'Criticidade'],
    primaryOptionalHeaders: [
      'Coluna1',
      'APAGAR',
      'Código Equipamento',
      'Código do MIS',
      'Código da Família',
      'Descrição da Família',
      'Classe',
      'Responsável',
      'Sensores',
      'Exclusão solicitada',
      'Justificativa da exclusão',
      'Aprovador da exclusão',
      'Data da aprovação',
    ],
    locationRequiredHeaders: ['TAG', 'Descrição'],
    locationOptionalHeaders: ['SEQ', 'Modalidade'],
  },
  mapping: {
    ignoredColumns: ['Coluna1', 'APAGAR'],
    assetKey: 'Código',
    locationKey: 'TAG',
    componentKey: 'TAG composta + proveniência do arquivo/aba/linha',
    componentCodeIsUnique: false,
    componentParentRule:
      'resolver segmento de Código após a localização; empate ou ausência bloqueia',
    sensorSource: 'Sensores (a ausência não comprova cobertura)',
    responsibleSource: 'Responsável (não inferir)',
    operationalStatusIsDerived: false,
    persistSourceWorkbook: false,
  },
  limits: {
    maxFileBytes: 10 * 1024 * 1024,
    maxRowsPerSheet: 10000,
    maxColumnsPerSheet: 100,
    maxZipEntries: 100,
    maxUncompressedBytes: 16 * 1024 * 1024,
    maxEntryUncompressedBytes: 8 * 1024 * 1024,
    maxCompressionRatio: 100,
  },
})
